name=input("Enter your name: ").strip()
age=input("Enter your age: ").strip()
city=input("Enter your city: ").strip()
job=input("Enter your job: ").strip()
hobby=input("Enter your hobby: ").strip()
print("--- Bio ---")
print(f"Hi! My name is {name} and I am {age} years old.")
print(f"I am from {city} and I work as a {job}.")
print(f"In my free time I love {hobby}.")